services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  Jb\Bundle\SimpleRestBundle\EventListener\JsonControllerListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  Jb\Bundle\SimpleRestBundle\EventListener\ApiExceptionListener:
    arguments:
      - "@logger"
      - "@serializer"
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  Jb\Bundle\SimpleRestBundle\EventListener\ZoneMatcherListener:
    arguments: []
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 248 }

  jb_simple_rest.zone_request_matcher:
    class: Symfony\Component\HttpFoundation\RequestMatcher